package com.myshow4all.student_internship_program.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

import java.time.LocalDate;

@Entity
@Data
public class InternshipDetails {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // An autogenerated ID for internship details

    private String traineeID;
    private String mentorName;
    private LocalDate fromDate;
    private LocalDate toDate;
    private LocalDate submittedOn;

    // Constructors, getters, and setters
}
