package com.myshow4all.student_internship_program.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;

@Entity
@Data
@Table
(
        name = "intern_details",
        schema = "student_internship_module_one",
        uniqueConstraints = @UniqueConstraint
                (
                        name = "trainee_id_unique",
                        columnNames = "trainee_id"
                )


)
public class InternshipDetails {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // An autogenerated ID for internship details


    @Column(name = "trainee_id", nullable = false)
    private String traineeID;

    @Column(nullable = false)
    private String mentorName;

    private LocalDate fromDate;
    private LocalDate toDate;
    private LocalDate submittedOn;

    // Constructors, getters, and setters
}
